#!/bin/bash 

x=0
while [ 1 ]; do
   #./test <some domaind> 8080 "text:(color,blue,red,brown,purple,black,white,horton)"
   ./test localhost 8080 "text:(color,blue,red,brown,purple,black,white,horton)"
   x=`expr $x + 1`
   echo "count:  $x"
   ./test localhost 8080 'text:("United States of America","High German",red,"United Kingdom",purple,black,white,"human activity")'
   x=`expr $x + 1`
   echo "count:  $x"
done

